### ISSUE TITLE
next_generation does not build on CentOS 8

### ISSUE THREAD

**Issue by sotiris-bos** [snuf/iomemory-vsl#53] opened 2019-11-15 17:20 UTC
### Bug description
next_generation does not build on CentOS 8 either with rpmbuild or DKMS. 5.1.28 works fine.

### How to reproduce
Checkout next_generation on CentOS 8 and try to build

### Environment information
1. 4.18.0-80.11.2.el8_0.x86_64
2. gcc (GCC) 8.2.1 20180905
3. CentOS 8
4. next_generation

Also, a list of dependencies would be nice to have. I will see if I can make a pull request and update the README.

Edit: Looks like a duplicate of https://github.com/snuf/iomemory-vsl/issues/47#issue-511100233
I did not check the closed Issues prior of posting..

**Comment by snuf** [comment] 2019-11-15 18:16
@sotiris-bos indeed it a dup of #47 problem is related to GCC, the fix is in 5.1.28, the problem is not kernel related.

No worries it just means I should get my ass in gear merging 5.1.28 and next_generation :\

**Closed** 2019-11-15 20:43 UTC
